### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by begank** [wayn111/newbee-mall-pro#7]
请问下面这里通过goodsId得到该商品的所有订单列表之后，将订单中的商品数量进行累加，累加之后得到的sum，为什么可以跟用户进行关联？ 这里得到的好像是某个商品的所有用户的购买数量累加吧？

`// 遍历订单商品
            for (OrderItemVO newBeeMallOrderItem : listMap.getOrDefault(orderId, Collections.emptyList())) {
                Long goodsId = newBeeMallOrderItem.getGoodsId();
                Long categoryId = newBeeMallOrderItem.getCategoryId();
                RelateDTO relateDTO = new RelateDTO();
                relateDTO.setUserId(newBeeMallOrder.getUserId());
                relateDTO.setProductId(goodsId);
                relateDTO.setCategoryId(categoryId);
                // 通过计算商品购买次数，来建立相似度
                List<OrderItemVO> list = goodsListMap.getOrDefault(goodsId, Collections.emptyList());
                int sum = list.stream().mapToInt(OrderItemVO::getGoodsCount).sum();
                relateDTO.setIndex(sum);
                relateDTOList.add(relateDTO);
            

> }`

**Comment by wayn111** [comment]
将用户之间下单的商品进行相似度计算，因为如果两个用户购买了同一个商品，那么我们认为这两个用户之间是存在联系并且都存在付费行为。

这里根据商品总购买次数，只是在这个商城目前环境中建立用户相似度的一个相对较好的指标
